spring.application.name=Management
server.port=8081
# Connection Credentials
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=library_management;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# Show generated SQL syntax in terminal logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Database DDL generation strategy (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=create-drop
# Database Dialect
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect